package ioMethodLib;

import java.util.ArrayList;
import java.util.HashMap;

//this is profile class which stores the call stack of each bug
//the call stack information can be easily generated by https://github.com/gousiosg/java-callgraph
public class callStackLib {
	public static HashMap<String, HashMap<String, ArrayList<String>>> callStackMap = new HashMap<String, HashMap<String, ArrayList<String>>>();
	
	
	static{
		String bugName = "mapreduce6991";
		HashMap<String, ArrayList<String>> callMap = new HashMap<String, ArrayList<String>>();
		{
			String caller = "TestProcfsBasedProcessTree: java.lang.String getRogueTaskPID()";
			ArrayList<String> callees = new ArrayList<String>();
			callees.add("TestProcfsBasedProcessTree: java.lang.String getPidFromPidFile(String)");
			callMap.put(caller, callees);
		}
		{
			String caller = "TestProcfsBasedProcessTree: void testProcessTree()";
			ArrayList<String> callees = new ArrayList<String>();
			callees.add("TestProcfsBasedProcessTree: java.lang.String getRogueTaskPID()");
			callees.add("TestProcfsBasedProcessTree$RogueTaskThread: void run()");
			callMap.put(caller, callees);
		}
		callStackMap.put(bugName, callMap);
	}
	
}
